# Generated by Django 2.2.3 on 2019-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_name',
            name='image_id',
            field=models.IntegerField(default=None),
        ),
    ]
