# Generated by Django 2.2.3 on 2019-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast_name', '0002_auto_20190815_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_name',
            name='cast_name_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
