# Generated by Django 2.2.3 on 2019-08-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('pic_link', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'pics',
            },
        ),
    ]
