# Generated by Django 2.2.3 on 2019-08-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pics',
            options={'verbose_name_plural': 'pics'},
        ),
        migrations.AlterField(
            model_name='pics',
            name='pic_link',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
