# Generated by Django 2.2.3 on 2019-08-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20190804_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pics',
            options={},
        ),
        migrations.AlterField(
            model_name='pics',
            name='image_id',
            field=models.CharField(max_length=50),
        ),
    ]
