# Generated by Django 2.2.3 on 2019-08-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20190804_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pics',
            options={'verbose_name_plural': 'pics'},
        ),
    ]
