# Generated by Django 2.2.3 on 2019-08-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_auto_20190815_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='image_id',
        ),
    ]
