# Generated by Django 2.2.3 on 2019-08-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quality_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_name_id', models.PositiveIntegerField()),
                ('quality_name', models.CharField(max_length=40)),
                ('priority', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'quality name',
            },
        ),
    ]
