# Generated by Django 2.2.3 on 2019-08-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies_list',
            options={'verbose_name_plural': 'movies_list'},
        ),
    ]
