# Generated by Django 2.2.3 on 2019-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0002_auto_20190804_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_list',
            name='cast_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='country_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='director_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='genres_list_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='writer_id',
            field=models.IntegerField(),
        ),
    ]
