# Generated by Django 2.2.3 on 2019-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0003_auto_20190805_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_list',
            name='Awards_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='language_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='season_id',
            field=models.IntegerField(),
        ),
    ]
