# Generated by Django 2.2.3 on 2019-08-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0004_auto_20190805_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_list',
            name='imdb_link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
