# Generated by Django 2.2.3 on 2019-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0005_auto_20190807_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies_list',
            old_name='genres_list_id',
            new_name='genre_list_id',
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='country_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='language_id',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='ratting',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='season_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movies_list',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
