# Generated by Django 2.2.3 on 2019-08-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0007_auto_20190815_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies_list',
            old_name='Award_id',
            new_name='award_id',
        ),
        migrations.RenameField(
            model_name='movies_list',
            old_name='IMDB_ratting',
            new_name='imdb_ratting',
        ),
        migrations.RenameField(
            model_name='movies_list',
            old_name='Release',
            new_name='release',
        ),
    ]
