from country_list.models import Country_list

c=Country_list(country_id=1,country_name="United States")
c.save()
c=Country_list(country_id=2,country_name="United Kingdom")
c.save()
c=Country_list(country_id=3,country_name="Canada")
c.save()
c=Country_list(country_id=4,country_name="France")
c.save()
c=Country_list(country_id=5,country_name="Germany")
c.save()
c=Country_list(country_id=6,country_name="Japan")
c.save()

c=Country_list(country_id=7,country_name="Australia")
c.save()
c=Country_list(country_id=8,country_name="Italy")
c.save()
c=Country_list(country_id=9,country_name="International")
c.save()
c=Country_list(country_id=10,country_name="Spain")
c.save()
c=Country_list(country_id=11,country_name="Hong-Kong")
c.save()
c=Country_list(country_id=12,country_name="China")
c.save()
c=Country_list(country_id=13,country_name="Ireland")
c.save()
c=Country_list(country_id=14,country_name="Korea")
c.save()

c=Country_list(country_id=15,country_name="India")
c.save()
c=Country_list(country_id=16,country_name="Belgium")
c.save()
c=Country_list(country_id=17,country_name="Denmark")
c.save()
c=Country_list(country_id=18,country_name="Sweden")
c.save()
c=Country_list(country_id=19,country_name="New-Zealand")
c.save()
c=Country_list(country_id=20,country_name="Netherlands")
c.save()
c=Country_list(country_id=21,country_name="South Africa")
c.save()
c=Country_list(country_id=22,country_name="Norway")
c.save()

c=Country_list(country_id=23,country_name="Mexico")
c.save()
c=Country_list(country_id=24,country_name="Switzerland")
c.save()
c=Country_list(country_id=25,country_name="Australia")
c.save()
c=Country_list(country_id=26,country_name="Czech Republic")
c.save()
c=Country_list(country_id=27,country_name="Brazil")
c.save()

c=Country_list(country_id=28,country_name="Russia")
c.save()
c=Country_list(country_id=29,country_name="Argentina")
c.save()
c=Country_list(country_id=30,country_name="Hungary")
c.save()

c=Country_list(country_id=31,country_name="Poland")
c.save()
c=Country_list(country_id=32,country_name="Finland")
c.save()
c=Country_list(country_id=33,country_name="Israel")
c.save()
c=Country_list(country_id=34,country_name="Romania")
c.save()
c=Country_list(country_id=35,country_name="Luxemberg")
c.save()

c=Country_list(country_id=36,country_name="Thailand")
c.save()
c=Country_list(country_id=37,country_name="Taiwan")
c.save()
