# Generated by Django 2.2.3 on 2019-08-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_auto_20190803_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'director'},
        ),
        migrations.AddField(
            model_name='director',
            name='director_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
