# Generated by Django 2.2.3 on 2019-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_auto_20190804_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='director_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='image_id',
            field=models.IntegerField(),
        ),
    ]
