# Generated by Django 2.2.3 on 2019-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.SmallIntegerField()),
                ('season_name', models.TextField()),
                ('eposide_id', models.PositiveIntegerField()),
                ('plot', models.TextField()),
            ],
        ),
    ]
