# Generated by Django 2.2.3 on 2019-08-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name_plural': 'season'},
        ),
    ]
