# Generated by Django 2.2.3 on 2019-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_auto_20190804_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='eposide_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_id',
            field=models.IntegerField(),
        ),
    ]
