# Generated by Django 2.2.3 on 2019-08-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.PositiveSmallIntegerField()),
                ('episode_no', models.PositiveSmallIntegerField()),
                ('episode_name', models.CharField(max_length=40)),
                ('server_list_id', models.PositiveSmallIntegerField()),
                ('views', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'cast',
            },
        ),
    ]
