# Generated by Django 2.2.3 on 2019-08-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0002_auto_20190804_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name_plural': 'episode'},
        ),
    ]
