# Generated by Django 2.2.3 on 2019-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0003_auto_20190804_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='server_list_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='views',
            field=models.IntegerField(),
        ),
    ]
