# Generated by Django 2.2.3 on 2019-08-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0004_auto_20190805_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='type',
        ),
    ]
