# Generated by Django 2.2.3 on 2019-08-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0006_episode_adult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='server_list_id',
            new_name='link_list_id',
        ),
        migrations.AddField(
            model_name='episode',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='filler',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
