# Generated by Django 2.2.3 on 2019-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_id', models.PositiveIntegerField()),
                ('quality_name', models.CharField(max_length=40)),
                ('quality_short_name', models.CharField(max_length=6)),
                ('quality_priority', models.PositiveIntegerField()),
            ],
        ),
    ]
