# Generated by Django 2.2.3 on 2019-08-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name_plural': 'quality'},
        ),
        migrations.RenameField(
            model_name='quality',
            old_name='quality_priority',
            new_name='quality_name_id',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='quality_name',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='quality_short_name',
        ),
    ]
