# Generated by Django 2.2.3 on 2019-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20190814_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality_name_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
