# Generated by Django 2.2.3 on 2019-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitle_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle_list',
            name='subtitle_name_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
