# Generated by Django 2.2.3 on 2019-08-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name_id', models.PositiveIntegerField(default=0)),
                ('image_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'director name',
            },
        ),
    ]
