# Generated by Django 2.2.3 on 2019-08-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director_name',
            name='director_name',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='director_name',
            name='image_id',
            field=models.IntegerField(default=None),
        ),
    ]
