# Generated by Django 2.2.3 on 2019-08-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190803_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name_plural': 'link'},
        ),
    ]
