# Generated by Django 2.2.3 on 2019-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20190804_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='server_name',
            new_name='server_name_id',
        ),
        migrations.AddField(
            model_name='link',
            name='server_type_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='subtitle',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
