# Generated by Django 2.2.3 on 2019-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20190807_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='link',
            name='link_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='Link', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='subtitle_list_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
