# Generated by Django 2.2.3 on 2019-08-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20190811_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='server_list_id',
            new_name='link_list_id',
        ),
    ]
