# Generated by Django 2.2.3 on 2019-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20190812_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='quality_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='server_type_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='subtitle_list_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
