# Generated by Django 2.2.3 on 2019-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20190813_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='server_name_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='upvote',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
