# Generated by Django 2.2.3 on 2019-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.PositiveSmallIntegerField()),
                ('language_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'language_name',
            },
        ),
    ]
