# Generated by Django 2.2.3 on 2019-08-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_name', '0002_auto_20190805_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_name',
            name='language_short_code',
            field=models.TextField(default='EN', max_length=5),
            preserve_default=False,
        ),
    ]
