# Generated by Django 2.2.3 on 2019-08-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'cast'},
        ),
        migrations.RemoveField(
            model_name='cast',
            name='actual_name',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='cast_name',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='image_id',
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_name_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cast',
            name='role',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
