# Generated by Django 2.2.3 on 2019-08-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_cast_cast_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'cast'},
        ),
    ]
