# Generated by Django 2.2.3 on 2019-08-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0005_cast_cast_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='actual_name',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='cast_name',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='image_id',
        ),
        migrations.AddField(
            model_name='cast',
            name='cast_name_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
