# Generated by Django 2.2.3 on 2019-08-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0006_auto_20190815_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='cast_movie_name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
