# Generated by Django 2.2.3 on 2019-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0007_cast_cast_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='cast_name_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cast',
            name='role',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
