# Generated by Django 2.2.3 on 2019-08-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0008_auto_20190815_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='cast_movie_name',
        ),
    ]
